#!/usr/bin/env python3
"""
Build an XSLT for validating one or more VOResource elements
against IVOA vocabularies.

This produces the file assets/validate/validateVocabularies.xsl and
is supposed to be executed whenever registry-relevant vocabularies
change (a few times a year at most).  From a checkout of benson::

    benson generate-vocabulary-xsl

Then git commit the updated XSLT and re-deploy.

[MD: this is fast enough that we could generate the XSLT at server
start; but when people do stand-alone validation, I think I'd rather
have the vocabularies, in effect, cached]

Configuration of what to validate lives in
assets/validate/vocabularyControlled.csv (see CONFIG_FILE).
"""

import functools
import json
import os
from pathlib import Path
from urllib import request

IVOA_VOCABULARY_ROOT = "http://www.ivoa.net/rdf/"

# CSV of vocabulary-controlled items (xpath, attpath, relative vocabulary
# url, mandatory).  xpath is the ri:Resource-relative xpath to the
# vocabulary-controlled element root, attpath the xpath (. for the element
# content, @attribute otherwise).  mandatory is a flag saying whether
# vocabulary adherence is a must as opposed to a should.
#
# I'm leving the type of the root element open; should we enforce
# ri:Resource here?  I don't think so.
CONFIG_FILE = "vocabularyControlled.csv"

XSL_BODY = """
<!-- Generated by benson.oai.vocabulary_xslt.py; do not edit by
hand. -->

<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ri="http://www.ivoa.net/xml/RegistryInterface/v1.0"
    xmlns:int="urn:ivoa:rofr-validator-internal"
    version="1.0">

    <xsl:template match="text()" mode="voccheck"/>

    {}
</xsl:stylesheet>
"""

FRAGMENT_TEMPLATE = """
    <int:{name}-terms>
        {terms}
    </int:{name}-terms>
    <int:{name}-deprecated>
        {deprecated}
    </int:{name}-deprecated>

    <xsl:key name="{name}-ok"
        match="/"
        use="document('')/xsl:stylesheet/int:{name}-terms/int:term"/>
    <xsl:key name="{name}-warn"
        match="/"
        use="document('')/xsl:stylesheet/int:{name}-deprecated/int:term"/>

    <xsl:template match="{xpath}" mode="voccheck">
        <xsl:variable name="term-given" select="normalize-space({attpath})"/>
        <xsl:choose>
            <xsl:when test="key('{name}-ok', $term-given)"/>

            <xsl:when test="key('{name}-warn', $term-given)">
                <xsl:call-template name="reportResult">
                    <xsl:with-param name="item">use-voc-{name}</xsl:with-param>
                    <xsl:with-param name="status">false</xsl:with-param>
                    <xsl:with-param name="type">warn</xsl:with-param>
                    <xsl:with-param name="desc"
                        >#<xsl:value-of select="$term-given"
                        /> deprecated in vocabulary {voc_url}
                    </xsl:with-param>
                </xsl:call-template>
            </xsl:when>

            <xsl:otherwise>
                <xsl:call-template name="reportResult">
                    <xsl:with-param name="item">use-voc-{name}</xsl:with-param>
                    <xsl:with-param name="status">false</xsl:with-param>
                    <xsl:with-param name="type">{miss_level}</xsl:with-param>
                    <xsl:with-param name="desc"
                        >#<xsl:value-of select="$term-given"
                        /> not in vocabulary {voc_url}
                    </xsl:with-param>
                </xsl:call-template>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
"""


def download_file(url, http_headers):
    voc_req = request.Request(url,
       headers=http_headers)
    with request.urlopen(voc_req) as src:
         return src.read()


def get_vocabulary(voc_name):
    """returns an IVOA vocabulary in its "desise" form.

    See Vocabularies in the VO 2 to see what is inside of this.
    """
    voc_src = download_file(
       IVOA_VOCABULARY_ROOT+voc_name,
       {"accept": "application/x-desise+json"})
    return json.loads(voc_src)


def make_validator_for(xpath, attpath, voc_name, mandatory):
    """returns XSL templates for validating elements in xpath/attpath
    against the IVOA vocabulary voc_name.

    If mandatory is false, bad terms are just flagged as warnings.
    """
    voc = get_vocabulary(voc_name)

    terms, deprecated = [], []
    for t, props in voc["terms"].items():
        if "deprecated" in props:
            deprecated.append(t)
        else:
            terms.append(t)

    return FRAGMENT_TEMPLATE.format(
        terms="\n        ".join(f"<int:term>{t}</int:term>" for t in terms),
        deprecated="\n        ".join(f"<int:term>{t}</int:term>"
            for t in deprecated),
        xpath=xpath,
        attpath=attpath,
        # there are vocabularies with path elements in them (sigh),
        # but name must be suitable for XML identifiers.
        name=voc_name.split("/")[-1],
        miss_level="fail" if mandatory else "warn",
        voc_url="http://www.ivoa.net/rdf/"+voc_name)


def read_config(validate_dir):
    # returns a list of tuples as per CONFIG_FILE.
    # we should probably do some input validation, too.
    import csv

    config_path = Path(validate_dir) / CONFIG_FILE
    with open(config_path, newline="") as config_source:
        return [tup
            for tup in csv.reader(config_source, skipinitialspace=True)]


def generate(validate_dir):
    """Fetch vocabularies and write validateVocabularies.xsl under validate_dir."""
    validate_dir = Path(validate_dir)
    conf = read_config(validate_dir)

    fragments = []
    for vocspec in conf:
        fragments.append(
            make_validator_for(*vocspec))

    out_path = validate_dir / "validateVocabularies.xsl"
    with open(out_path, "w") as f:
        f.write((XSL_BODY.format(
            "\n\n".join(fragments))))
    return out_path


def main():
    generate(".")


if __name__=="__main__":
    main()

# vim:et:sw=4:sta
