#!/usr/bin/env python3
"""
Build an XSLT for validating one or more VOResource elements
against IVOA vocabularies.

This produces the file assets/validate/validateVocabularies.xsl and
is supposed to be executed in validate whenever registry-relevant
vocabularies change.  The current plan is that in a checkout of benson,
you do::

    cd assets/validate
    python ../../src/benson/oai/vocabulary_xslt.py

Then git commit your changes and re-deploy.

[MD: this is fast enough that we could generate the XSLT at server
start; but when people do stand-alone validation, I think I'd rather
have the vocabularies, in effect, cached]

There is configuration in here that probably should be put into an
external file;  see VOCABULARY_CONTROLLED below..
"""

import functools
import json
import os
from urllib import request

IVOA_VOCABULARY_ROOT = "http://www.ivoa.net/rdf/"

# The following string configures what to validate; it should go
# into an appropriate string.  The fields are:
# xpath, attpath, relative vocabulary url, mandatory
#
# xpath is the ri:Resource-relative xpath to the vocabulary-controlled
# element root, attpath the xpath (. for the element content, @attribute
# otherwise).   mandatory is a flag saying whether vocabulary adherence
# is a must as opposed to a should.

# I'm leving the type of the root element open; should we enfoce
# ri:Resource here?  I don't think so.
VOCABULARY_CONTROLLED = (
"/*/curation/date, @role, voresource/date_role, True\n"
"/*/content/contentLevel, ., voresource/content_level, True\n"
"/*/content/type, ., voresource/content_type, True\n"
"/*/content/relationship/relationshipType, ., voresource/relationship_type, True\n"
"/*/content/subject, ., uat, False\n"
"/*/productTypeServed, ., product-type, True\n"
"/*/dataSource, ., data-source, True\n"
"/*/coverage/waveband, ., messenger, True\n")


XSL_BODY = """
<!-- Generated by benson.oai.vocabulary_xslt.py; do not edit by
hand. -->

<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ri="http://www.ivoa.net/xml/RegistryInterface/v1.0"
    xmlns:int="urn:ivoa:rofr-validator-internal"
    version="1.0">

    <xsl:template match="text()" mode="voccheck"/>

    {}
</xsl:stylesheet>
"""

FRAGMENT_TEMPLATE = """
    <int:{name}-terms>
        {terms}
    </int:{name}-terms>
    <int:{name}-deprecated>
        {deprecated}
    </int:{name}-deprecated>

    <xsl:key name="{name}-ok"
        match="/"
        use="document('')/xsl:stylesheet/int:{name}-terms/int:term"/>
    <xsl:key name="{name}-warn"
        match="/"
        use="document('')/xsl:stylesheet/int:{name}-deprecated/int:term"/>

    <xsl:template match="{xpath}" mode="voccheck">
        <xsl:variable name="term-given" select="normalize-space({attpath})"/>
        <xsl:choose>
            <xsl:when test="key('{name}-ok', $term-given)"/>

            <xsl:when test="key('{name}-warn', $term-given)">
                <xsl:call-template name="reportResult">
                    <xsl:with-param name="item">use-voc-{name}</xsl:with-param>
                    <xsl:with-param name="status">false</xsl:with-param>
                    <xsl:with-param name="type">warn</xsl:with-param>
                    <xsl:with-param name="desc"
                        >#<xsl:value-of select="$term-given"
                        /> deprecated in vocabulary {voc_url}
                    </xsl:with-param>
                </xsl:call-template>
            </xsl:when>

            <xsl:otherwise>
                <xsl:call-template name="reportResult">
                    <xsl:with-param name="item">use-voc-{name}</xsl:with-param>
                    <xsl:with-param name="status">false</xsl:with-param>
                    <xsl:with-param name="type">{miss_level}</xsl:with-param>
                    <xsl:with-param name="desc"
                        >#<xsl:value-of select="$term-given"
                        /> not in vocabulary {voc_url}
                    </xsl:with-param>
                </xsl:call-template>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
"""


def download_file(url, http_headers):
    voc_req = request.Request(url,
       headers=http_headers)
    with request.urlopen(voc_req) as src:
         return src.read()


def get_vocabulary(voc_name):
    """returns an IVOA vocabulary in its "desise" form.

    See Vocabularies in the VO 2 to see what is inside of this.
    """
    voc_src = download_file(
       IVOA_VOCABULARY_ROOT+voc_name,
       {"accept": "application/x-desise+json"})
    return json.loads(voc_src)


def make_validator_for(xpath, attpath, voc_name, mandatory):
    """returns XSL templates for validating elements in xpath/attpath
    against the IVOA vocabulary voc_name.

    If mandatory is false, bad terms are just flagged as warnings.
    """
    voc = get_vocabulary(voc_name)

    terms, deprecated = [], []
    for t, props in voc["terms"].items():
        if "deprecated" in props:
            deprecated.append(t)
        else:
            terms.append(t)

    return FRAGMENT_TEMPLATE.format(
        terms="\n        ".join(f"<int:term>{t}</int:term>" for t in terms),
        deprecated="\n        ".join(f"<int:term>{t}</int:term>"
            for t in deprecated),
        xpath=xpath,
        attpath=attpath,
        # there are vocabularies with path elements in them (sigh),
        # but name must be suitable for XML identifiers.
        name=voc_name.split("/")[-1],
        miss_level="fail" if mandatory else "warn",
        voc_url="http://www.ivoa.net/rdf/"+voc_name)


def read_config():
    # returns a list of tuples as per VOCABULARY_CONTROLLED above.
    # we should probably read from the file system in some way and then
    # do some input validation, too.
    import csv, io

    config_source = io.StringIO(VOCABULARY_CONTROLLED)
    return [tup
        for tup in csv.reader(config_source, skipinitialspace=True)]


def main():
    conf = read_config()

    fragments = []
    for vocspec in conf:
        fragments.append(
            make_validator_for(*vocspec))

    with open("validateVocabularies.xsl", "w") as f:
        f.write((XSL_BODY.format(
            "\n\n".join(fragments))))


if __name__=="__main__":
    main()

# vim:et:sw=4:sta
